name = "Raspberry Flavoured"
author = "raspmary"
version = "3.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "481685504bae119e089531b0f11f8e119f2314aa209f4a516db64104bd6504e3"

[versions]
forge = "43.5.1"
minecraft = "1.19.2"
