name = "Raspberry Flavoured"
author = "raspmary"
version = "3.0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "98b593e3b11f0e7c285ea6575d3fea75bd1ee507c50b52d5c7446eb76fe03133"

[versions]
forge = "43.4.12"
minecraft = "1.19.2"
