name = "Raspberry Flavoured"
author = "raspmary"
version = "3.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "225f912ab99e3bb435bb7801e13756156cee7dd3131b9674912482699843fd70"

[versions]
forge = "43.4.12"
minecraft = "1.19.2"
