name = "Raspberry Flavoured"
author = "raspmary"
version = "3.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "16b2e695f7fea71ad9b9ca010cf99bf16a6c24edfed7304df5f87725319b0e75"

[versions]
forge = "43.4.12"
minecraft = "1.19.2"
